### ISSUE TITLE
MeshLine.save

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#146]
```python
from skfem import MeshLine
MeshLine().save('1.msh')
```
raises
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geordie/.py3.7/skfem/src/scikit-fem/skfem/mesh/mesh.py", line 274, in save
    meshio.write(filename, mesh)
  File "/home/geordie/.py3.7/skfem/src/meshio/meshio/helpers.py", line 211, in write
    assert value.shape[1] == num_nodes_per_cell[key]
KeyError: 'none'
```

**Comment by gdmcbain** [comment]
The `KeyError` is because `MeshLine` lacks `meshio_type`.
```python
mesh = MeshLine()
mesh.meshio_type = 'line'
mesh.save('1.msh')
```
works (but not correctly).

**Comment by gdmcbain** [comment]
Well, ‘not correctly’ might be subjective.  Whereas `Mesh2D.save` appends a zero _z_-coordinate to each point, `MeshLine.save` (with `meshio_type = 'line'`) appends _y_ and _z_-coordinates equal to the _x_; e.g.
```python
from skfem import MeshLine
import meshio

mesh = MeshLine()
mesh.meshio_type = 'line'

mesh.save('1.msh')

print(meshio.read('1.msh').points.T)
```
So the one-dimensional mesh is embedded in ℝ³ along _x_ = _y_ = _z_ rather than along _y_ = _z_ = 0.

This second problem is to do with `meshio.write` or rather `meshio.msh_io.write` (i.e. probably differs according to the file format output) rather than `skfem.mesh.save` itself.

**Comment by gdmcbain** [comment]
Trying MEDIT .mesh as the output format uncovers a third problem:
```python
mesh = MeshLine()
mesh.meshio_type = 'line'
mesh.save('1.mesh')
```
raises
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geordie/.py3.7/skfem/src/scikit-fem/skfem/mesh/mesh.py", line 274, in save
    meshio.write(filename, mesh)
  File "/home/geordie/.py3.7/skfem/src/meshio/meshio/helpers.py", line 227, in write
    return interface.write(filename, mesh, *args, **_kwargs)
  File "/home/geordie/.py3.7/skfem/src/meshio/meshio/medit_io.py", line 119, in write
    version = {numpy.dtype(c_float): 1, numpy.dtype(c_double): 2}[mesh.points.dtype]
KeyError: dtype('int64')
```
The points of a `MeshLine()` are int rather than float.
```python
mesh.p = mesh.p.astype(float)
mesh.save('1.mesh')
```
works.
