### ISSUE TITLE
Mesh.save changes break ex18 and maybe others

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#212]
After pulling the weekend's changes,
```shell
python docs/examples/ex18.py 
```
raises
```
Traceback (most recent call last):
  File "docs/examples/ex18.py", line 64, in <module>
    mesh.save(f'{name}_velocity.vtk', velocity[basis['u'].nodal_dofs].T)
  File "/home/geordie/src/scikit-fem/skfem/mesh/mesh.py", line 287, in save
    raise ValueError("point_data should be "
ValueError: point_data should be a dictionary of ndarrays.
```

I expect this'll be easy enough to fix, thanks to the informative message.

**Comment by gdmcbain** [comment]
Others include ex09 and ex24.
