### ISSUE TITLE
ex27 needs updating to read from_meshio

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#216]
```
>python docs\examples\ex27.py
Traceback (most recent call last):
  File "docs\examples\ex27.py", line 226, in <module>
    bfs = BackwardFacingStep(lcar=.2)
  File "docs\examples\ex27.py", line 65, in __init__
    self.mesh = self.make_mesh(self.make_geom(length, lcar))
  File "docs\examples\ex27.py", line 112, in make_mesh
    return MeshTri.from_meshio(generate_mesh(geom, dim=2))
AttributeError: type object 'MeshTri' has no attribute 'from_meshio'
```

**Comment by gdmcbain** [comment]
I expect it just needs updating like ex24, as in 6825914481681f6bf9731d98e70f17fd6bfe73fd.
