### ISSUE TITLE
Tests using pygmsh fail due to upstream changes

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#482]
This is due to the commit: https://github.com/nschloe/pygmsh/commit/ed581be373ed7357b4bb83183749a10760034892#diff-bc0dadc6113a14c1c7891320765ee767

**Comment by kinnala** [comment]
Seems to be a simple enough fix: `generate_mesh` was turned into a method of `Geometry`.

**Comment by kinnala** [comment]
Wow, actually this new `pygmsh` release using `gmsh` package fails pretty fatally on my operating system:
```
        if handle is None:
>           self._handle = _dlopen(self._name, mode)
E           OSError: libXcursor.so.1: cannot open shared object file: No such file or directory
```

**Comment by kinnala** [comment]
#365 causes the tests to fail but #360 is the PR which causes this to fail on my laptop.

**Comment by kinnala** [comment]
I need to look into this later, I'm now a bit busy with the grant application.

**Comment by kinnala** [comment]
Ok, the grant deadline was extended so I can now look into this.

**Comment by kinnala** [comment]
```
(vedoenv) conda-shell-chrootenv:tom@tunkki:~/src/scikit-fem$ python -c "import gmsh"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/.conda/envs/vedoenv/lib/python3.8/site-packages/gmsh-4.6.0-Linux64-sdk/lib/gmsh.py", line 39, in <module>
    lib = CDLL(libpath)
  File "/home/tom/.conda/envs/vedoenv/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libXcursor.so.1: cannot open shared object file: No such file or directory
```

**Comment by kinnala** [comment]
I'm getting some of the required libraries from nixpkgs but it seems that the binaries distributed in `gmsh` package are compiled against some newer versions of xorg-related libraries that I can easily to install.

Workaround is to restrict to an older version of pygmsh which I'm going to do now. Maybe this is finally the reason to do #333 .

**Comment by kinnala** [comment]
Pinned pygmsh to 6.1.1. Making another issue to support 7.0.0.
