### ISSUE TITLE
vrot broken

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#548]
Running
```shell
python docs/examples/ex20.py
```
 raises
```
psi0 = 0.015846568093739626 (cf. exact = 1/64 = 0.015625)
Traceback (most recent call last):
  File "/home/gmcbain/src/scikit-fem/docs/examples/ex20.py", line 71, in <module>
    velocity = asm(
  File "/home/gmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/assembly/__init__.py", line 62, in asm
    return form.assemble(*args, **kwargs)
  File "/home/gmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/assembly/form/linear_form.py", line 40, in assemble
    data[ixs] = self._kernel(vbasis.basis[i], w, dx)
  File "/home/gmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/assembly/form/linear_form.py", line 45, in _kernel
    return np.sum(self.form(*v, w) * dx, axis=1)
  File "/home/gmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/models/general.py", line 19, in vrot
    return dot(v, curl(w.w))
  File "/home/gmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/helpers.py", line 31, in curl
    if u.curl is not None:
AttributeError: 'numpy.ndarray' object has no attribute 'curl'
```

This is missed by the tests since it's only run `if __name__ == "__main__"`.

I think the problem is that `w.w` is an `ndarray` whereas we were expecting a `DiscreteField` like `w["w"]`.

**Comment by gdmcbain** [comment]
A simple fix is in #549, but it's a bit subtle.  On first looking at `skfem.models.general.vrot` and seeing `w.w`, I had thought that the same fix would be required for `rot`

https://github.com/kinnala/scikit-fem/blob/2957f0443be445d975c0299b9bef02ed4e2f5886/skfem/models/general.py#L12-L14

but no, because it doesn't have its curl taken there, so exx 18, 27, 30 run fine.

I see that 

https://github.com/kinnala/scikit-fem/blob/2957f0443be445d975c0299b9bef02ed4e2f5886/skfem/helpers.py#L29-L36

is expecting a `DiscreteField`.  Should `w.w` be one?
