### ISSUE TITLE
init mesh from points and cells

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#570]
In the main readme, I find a number of examples on how to initialize a mesh from files and from points (how? convex hull?), but not from points and cells. I'd say that'd be a pretty common case, right? Perhaps you can consider adding this to the readme, or otherwise just drop a hint here.

**Comment by kinnala** [comment]
Sure, that sounds reasonable. I'll do it later today but here is a hint:
```python
m = MeshTri(points, cells)
```
Here `points` must have the shape 2 x number of points and `cells` 3 x number of cells.

**Comment by nschloe** [comment]
Not working:
```python
import meshzoo
from skfem import BilinearForm, ElementTetP2, InteriorBasis, MeshTri
from skfem.helpers import dot, grad

@BilinearForm
def laplace(u, v, w):
    return dot(grad(u), grad(v))

points, cells = meshzoo.rectangle_tri((-1.0, -1.0), (1.0, 1.0), 20)
print(points.shape)
print(cells.shape)
mesh = MeshTri(points.T, cells.T)

basis = InteriorBasis(mesh, ElementTetP2())
A = laplace.assemble(basis)
```
```
(400, 2)
(722, 3)
Traceback (most recent call last):
  File "/home/nschloe/rcs/betterspy/test/test_betterspy.py", line 74, in <module>
    test_readme_images()
  File "/home/nschloe/rcs/betterspy/test/test_betterspy.py", line 53, in test_readme_images
    basis = InteriorBasis(mesh, ElementTetP2())
  File "/home/nschloe/.local/lib/python3.9/site-packages/skfem/assembly/basis/interior_basis.py", line 60, in __init__
    super(InteriorBasis, self).__init__(mesh,
  File "/home/nschloe/.local/lib/python3.9/site-packages/skfem/assembly/basis/basis.py", line 43, in __init__
    self.dofs = Dofs(mesh, elem)
  File "/home/nschloe/.local/lib/python3.9/site-packages/skfem/assembly/dofs.py", line 187, in __init__
    np.arange(element.edge_dofs * topo.nedges,
  File "/home/nschloe/.local/lib/python3.9/site-packages/skfem/mesh/mesh.py", line 154, in nedges
    return int(self.edges.shape[1])
AttributeError: 'MeshTri' object has no attribute 'edges'
```

**Comment by kinnala** [comment]
It seems you are using ElementTetP2. Try ElementTriP2.

I have no idea why InteriorBasis constructor does not check for this though (it should).

**Comment by nschloe** [comment]
> It seems you are using ElementTetP2. Try ElementTriP2.

Whoops, my mistake. Yeah, this should probably be checked, too.

**Comment by nschloe** [comment]
Cool, thanks!
