### ISSUE TITLE
trace regression

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#686]
MWE:
```python
mesh = MeshQuad().with_boundaries({"left": lambda x: x[0] == 0.0})
basis = CellBasis(mesh, ElementQuad1())
left = BoundaryFacetBasis(mesh, basis.elem, facets=mesh.boundaries["left"])
trace = left.trace(basis.doflocs[1], lambda x: x[1])
print(trace[1])
```

This works with `pip install scikit-fem<3.2`, printing `[0.5]`, but fails in `pip install 3.2` or current master (e7196f61b59c61706ef105de35b3cc0453fb8c72 ), raising an `IndexError`:
```

Traceback (most recent call last):
  File "C:\Users\gmcbain\mwe.py", line 6, in <module>
    trace = left.trace(basis.doflocs[1], lambda x: x[1])
  File "C:\Users\gmcbain\Miniconda3\envs\skfem\lib\site-packages\skfem\assembly\basis\boundary_facet_basis.py", line 179, in trace
    CellBasis(target_meshcls(projection(p), t), elemcls()),
  File "<string>", line 11, in __init__
  File "C:\Users\gmcbain\Miniconda3\envs\skfem\lib\site-packages\skfem\mesh\mesh_line_1.py", line 23, in __post_init__
    super().__post_init__()
  File "C:\Users\gmcbain\Miniconda3\envs\skfem\lib\site-packages\skfem\mesh\mesh.py", line 417, in __post_init__
    if self.doflocs.shape[1] > 1000:
IndexError: tuple index out of range
```

I think it's something to do with whether the points defining a `MeshLine1` have `ndim` 1, or 2 with `shape[0] == 1`; accepting the former is a special case still accepted by the main `MeshLine1` constructor.

The example does run (in 3.1, 3.2, and current) if the `projection` passed to `left.trace` is changed to `lambda x: x[1:]`, so a makeshift is to change old code.

**Comment by gdmcbain** [comment]
Uh-oh, `git bisect` says:
```
26af4c44e05e61c2b948b7b33bb39a7abbf552b5 is the first bad commit
commit 26af4c44e05e61c2b948b7b33bb39a7abbf552b5
Author: G. D. McBain <gdmcbain@protonmail.com>
Date:   Wed Jun 30 10:48:57 2021 +1000

    super post-init; fixes #663

 skfem/mesh/mesh_line_1.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```
